### ISSUE TITLE
⚛️ Revisit font sizes

### ISSUE THREAD

**Issue by vdedios** [42AGV/ft_transcendence#101]
- [x] Fix broken fonts in `Text` component

And, also:
 
- [x] Unify font sizes from Figma to application.
- [x] Add the `line-height` property to the text classes to match the sizes from Figma
- [x] Get rid off harcoded text font sizes in `Text` component

**Comment by gbudau** [comment]
Thank you, good catch! We could use classes instead of hardcoding the sizes in the Text component.

If the sizes are small only for the desktop, we could use media queries and match the values with the ones we have for desktop text in Figma.

Either setting a bigger base font
```
@media (min-width: 768px) {
  :root {
    font-size: 20px 
  }
}
```


Or setting the desktop size in each text class

```
@media (min-width: 768px) {
  .title-bold {
    font-size: 3rem;
  }
   
  .subtitle-bold {	  
    font-size: 2.5rem;	    
  }

  ...
}
```

And if the sizes are smaller for both mobile and desktop, we could update both default sizes in the index.css and Figma, and I think we also have to use media queries in this case.

**Comment by vdedios** [comment]
Part of this task have been solved in https://github.com/42AGV/ft_transcendence/pull/96#event-7005111752

**Comment by gbudau** [comment]
- [ ] Add the `line-height` property from Figma to the text classes from index.css
