### ISSUE TITLE
⚛️ Fix non encrypted password in the request body upon login in

### ISSUE THREAD

**Issue by fizcamposancos** [42AGV/ft_transcendence#182]
In request body, password can be plainly seen when the information is sent to the API

![image](https://user-images.githubusercontent.com/56964234/190253385-62b57d8d-8dc2-4034-b80a-48dd5d80abc0.png)

**Comment by gbudau** [comment]
I think this is not an issue.

In development mode, we use HTTP, but in production, we could use HTTPS, and the request and response will be encrypted using SSL.

Also, since we use a POST request, we don't leak the payload within the query string of the requested URL.

https://stackoverflow.com/questions/1582894/how-to-send-password-securely-over-http

**Comment by vdedios** [comment]
Totally agree with @gbudau as stated in https://github.com/42AGV/ft_transcendence/pull/177#discussion_r971299725
