### ISSUE TITLE
page 404 not found wrong HTTP status code

### ISSUE THREAD

**Issue by Damrod** [42AGV/ft_transcendence#323]
When browsing non existing/unrouted pages, webapp will redirect us to the 404 not found page, this is okay. But the HTTP status is set to 200 ok, whereas is should match the 404 status we would expect. Maybe nginx error pages would solve the problem?

![Screenshot from 2022-11-10 01-56-13](https://user-images.githubusercontent.com/2774420/200967476-bd1a67f8-0f3f-4ada-8fd1-50a0aff9a968.png)

**Comment by vdedios** [comment]
I think that request shouldn't be a 404 since the resource we are requesting to Nginx exists (the webapp itself). This a information we provide within the SPA, warning the user about the route they try to navigate to doesn't exist. What do you think about removing the `404`, something like "Page requested don't exist" could be more accurate?
